"""Add policy compiler and agent catalog.

Revision ID: 7b285f2ac567
Revises: e081a7f98374
Create Date: 2026-09-11 21:12:02.145924
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision: str = "7b285f2ac567"
down_revision: str | Sequence[str] | None = "e081a7f98374"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create policy and Agent Catalog truth without touching checkpoints."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_definitions",
        sa.Column("code", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_agent_definitions_category"), "agent_definitions", ["category"], unique=False
    )
    op.create_table(
        "agent_versions",
        sa.Column("agent_code", sa.String(length=96), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("configuration_json", sa.Text(), nullable=False),
        sa.Column("capabilities_json", sa.Text(), nullable=False),
        sa.Column("input_schema_json", sa.Text(), nullable=False),
        sa.Column("output_schema_json", sa.Text(), nullable=False),
        sa.Column("risk", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_code"], ["agent_definitions.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("agent_code", "version"),
    )
    agent_definitions = sa.table(
        "agent_definitions",
        sa.column("code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("category", sa.String()),
    )
    agent_versions = sa.table(
        "agent_versions",
        sa.column("agent_code", sa.String()),
        sa.column("version", sa.String()),
        sa.column("prompt_template", sa.Text()),
        sa.column("configuration_json", sa.Text()),
        sa.column("capabilities_json", sa.Text()),
        sa.column("input_schema_json", sa.Text()),
        sa.column("output_schema_json", sa.Text()),
        sa.column("risk", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    packs = [
        ("planner", "Planner Agent", "coordination"),
        ("executive_strategy", "Executive & Strategy Agent", "business"),
        ("pmo", "PMO & Project Management Agent", "business"),
        ("construction", "Construction Operations Agent", "industry"),
        ("events", "Events Operations Agent", "industry"),
        ("risk_compliance", "Risk & Compliance Agent", "safety_risk_governance"),
        ("product_software", "Product & Software Development Agent", "business"),
        ("automation_integrations", "Automation & Integrations Agent", "automation_integrations"),
        ("finance", "Finance Agent", "business"),
        ("it_operations", "IT Operations Agent", "business"),
        ("people_hr", "People & HR Agent", "business"),
        ("procurement_vendors", "Procurement & Vendors Agent", "business"),
        ("legal", "Legal Agent", "safety_risk_governance"),
        ("sales_crm", "Sales & CRM Agent", "business"),
        ("marketing", "Marketing Agent", "execution_content"),
        ("customer_success", "Customer Support & Success Agent", "business"),
        ("operations_facilities", "Operations & Facilities Agent", "business"),
        ("quality_hse", "Quality & HSE Agent", "safety_risk_governance"),
        ("knowledge_documents", "Knowledge & Documents Agent", "knowledge_research"),
        ("communications", "Communications Agent", "execution_content"),
        ("department_operations", "Department Operations Agent", "business"),
        ("review_safety_recovery", "Review, Safety & Recovery Agent", "safety_risk_governance"),
    ]
    now = datetime.now(UTC)
    op.bulk_insert(
        agent_definitions,
        [
            {"code": code, "name": name, "description": name, "category": category}
            for code, name, category in packs
        ],
    )
    op.bulk_insert(
        agent_versions,
        [
            {
                "agent_code": code,
                "version": "1.0.0",
                "prompt_template": "system-template-v1",
                "configuration_json": "{}",
                "capabilities_json": "[]",
                "input_schema_json": "{}",
                "output_schema_json": "{}",
                "risk": "medium",
                "created_at": now,
            }
            for code, _name, _category in packs
        ],
    )
    op.create_table(
        "agent_approval_chains",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("agent_code", sa.String(length=96), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("risk", sa.String(length=24), nullable=False),
        sa.Column("target_system", sa.String(length=96), nullable=False),
        sa.Column("chain_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_code"],
            ["agent_definitions.code"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_approval_chains_organization_id"),
        "agent_approval_chains",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "authorization_decision_audit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id_hash", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("matched_rule_ids_json", sa.Text(), nullable=False),
        sa.Column("obligations_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authorization_decision_audit_actor_id"),
        "authorization_decision_audit",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authorization_decision_audit_correlation_id"),
        "authorization_decision_audit",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authorization_decision_audit_organization_id"),
        "authorization_decision_audit",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "authorization_policy_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("effect", sa.String(length=16), nullable=False),
        sa.Column("actions_json", sa.Text(), nullable=False),
        sa.Column("resource_types_json", sa.Text(), nullable=False),
        sa.Column("resource_ids_json", sa.Text(), nullable=False),
        sa.Column("role_codes_json", sa.Text(), nullable=False),
        sa.Column("actor_ids_json", sa.Text(), nullable=False),
        sa.Column("department_ids_json", sa.Text(), nullable=False),
        sa.Column("team_ids_json", sa.Text(), nullable=False),
        sa.Column("project_ids_json", sa.Text(), nullable=False),
        sa.Column("geography_json", sa.Text(), nullable=False),
        sa.Column("classification_ceiling", sa.String(length=32), nullable=False),
        sa.Column("owner_only", sa.Boolean(), nullable=False),
        sa.Column("utc_hour_start", sa.Integer(), nullable=True),
        sa.Column("utc_hour_end", sa.Integer(), nullable=True),
        sa.Column("obligations_json", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authorization_policy_rules_organization_id"),
        "authorization_policy_rules",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authorization_policy_rules_policy_version"),
        "authorization_policy_rules",
        ["policy_version"],
        unique=False,
    )
    op.create_index(
        "ix_policy_rules_effective",
        "authorization_policy_rules",
        ["organization_id", "policy_version", "active"],
        unique=False,
    )
    op.create_table(
        "organization_agents",
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("agent_code", sa.String(length=96), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("installed_by", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_code"],
            ["agent_definitions.code"],
        ),
        sa.ForeignKeyConstraint(
            ["installed_by"],
            ["identity_users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("organization_id", "agent_code"),
        sa.UniqueConstraint("organization_id", "agent_code", name="uq_org_agent"),
    )
    op.create_table(
        "agent_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("agent_code", sa.String(length=96), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=False),
        sa.Column("classification_ceiling", sa.String(length=32), nullable=False),
        sa.Column("data_domains_json", sa.Text(), nullable=False),
        sa.Column("quota_json", sa.Text(), nullable=False),
        sa.Column("budget_json", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["identity_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_code"],
            ["organization_agents.organization_id", "organization_agents.agent_code"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_agent_assignment_org_id"),
    )
    op.create_index(
        op.f("ix_agent_assignments_organization_id"),
        "agent_assignments",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "agent_action_grants",
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("effect", sa.String(length=16), nullable=False),
        sa.Column("obligations_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "assignment_id"],
            ["agent_assignments.organization_id", "agent_assignments.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("organization_id", "assignment_id", "action"),
    )
    op.create_table(
        "agent_assignment_attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("attachment_type", sa.String(length=32), nullable=False),
        sa.Column("reference_id", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "assignment_id"],
            ["agent_assignments.organization_id", "agent_assignments.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop F2-owned tables in reverse dependency order."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_assignment_attachments")
    op.drop_table("agent_action_grants")
    op.drop_index(op.f("ix_agent_assignments_organization_id"), table_name="agent_assignments")
    op.drop_table("agent_assignments")
    op.drop_table("organization_agents")
    op.drop_index("ix_policy_rules_effective", table_name="authorization_policy_rules")
    op.drop_index(
        op.f("ix_authorization_policy_rules_policy_version"),
        table_name="authorization_policy_rules",
    )
    op.drop_index(
        op.f("ix_authorization_policy_rules_organization_id"),
        table_name="authorization_policy_rules",
    )
    op.drop_table("authorization_policy_rules")
    op.drop_index(
        op.f("ix_authorization_decision_audit_organization_id"),
        table_name="authorization_decision_audit",
    )
    op.drop_index(
        op.f("ix_authorization_decision_audit_correlation_id"),
        table_name="authorization_decision_audit",
    )
    op.drop_index(
        op.f("ix_authorization_decision_audit_actor_id"), table_name="authorization_decision_audit"
    )
    op.drop_table("authorization_decision_audit")
    op.drop_index(
        op.f("ix_agent_approval_chains_organization_id"), table_name="agent_approval_chains"
    )
    op.drop_table("agent_approval_chains")
    op.drop_table("agent_versions")
    op.drop_index(op.f("ix_agent_definitions_category"), table_name="agent_definitions")
    op.drop_table("agent_definitions")
    # ### end Alembic commands ###
